site_name: プロト屋
site_url: https://www.proto-ya.com
copyright: "&copy; 2025 Yasuhisa Hironaka"
theme:
  name: material
  palette:
      primary: pink
  font:
    text: Noto Sans JP
    code: ospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace;
  logo: images/protoya-logo-white.svg
  favicon: images/favicon.svg
  language: ja
  features:
    - navigation.tabs
    - header.autohide
    - navigation.path
    - navigation.sections
    - content.code.copy
  custom_dir: overrides
plugins:
  - search
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
  consent:
    title: Cookie consent
    description:
      This website uses cookies to improve the usability of the site.By browsing the site, you must agree to the use of cookies.</br>
      このウェブサイトでは、サイトの利便性向上を目的に、クッキーを使用しています。サイトを閲覧いただく際には、クッキーの使用に同意いただく必要があります。
  generator: false
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - javascripts/highlight.js  
extra_css:
  - css/style.css
  - css/ogp-link.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/vs.css
nav:
  - Home:
    - home.md
    - about.md
    - 表紙: index.md
  - 業務事例:
    - case/index.md
    - case/aws-account-migration.md
    - case/modernization-proposal.md
    - case/cicd-replace.md
    - case/private-cloud-to-aws-migration.md
    - case/erp-package-development.md
  - 技術ノート:
    - tech-notes/index.md
    - tech-notes/making-protoya-portfolio-site.md
    - tech-notes/how-to-make-ogp-image.md
    - tech-notes/MWAA-as-modern-IT-operations-management.md
