name: OracleCloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout Repository
        uses: actions/checkout@v3

      # GA4_TAGの値をSecretsの値に置き換え
      - name: Replace GA4_TAG with secrets
        run: sed -i "s/G-XXXXXXXXXX/${{ secrets.GA4_TAG }}/g" mkdocs.yml

      # Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3
     
      # 必要なパッケージをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # MkDocsサイトをビルド
      - name: Build MkDocs Site
        run: mkdocs build

      # サーバにデプロイ
      - name: Deploy to Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          source: "site/*"
          target: "/usr/share/nginx/protoya/"

      # OGPサーバ、デプロイ
      - name: Deploy OGP-Server to Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.KEY }}
          source: "ogp-server/*"
          target: "/usr/share/nginx/protoya/"

      # OGPサーバ、デプロイ用SSH接続
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # OGPサーバ、npmセットアップ
      - name: Install npm packages on remote server
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd /usr/share/nginx/protoya/ogp-server/
            npm install express axios cheerio cors
            pm2 restart server.js
          EOF